apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://${CONTAINER_INFLUXDB}:${PORT_INFLUXDB}
    isDefault: false
    editable: true
    jsonData:
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      version: "Flux"
      tlsSkipVerify: true
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
